 
---
  linters-settings:
    dupl:
      threshold: 100
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
    gocyclo:
      min-complexity: 15
    golint:
      min-confidence: 0.8
    govet:
      check-shadowing: true
    lll:
      line-length: 140
    maligned:
      suggest-new: true
    misspell:
      locale: US
  
  linters:
    disable-all: true
    enable:
      - bodyclose
      - deadcode
      - depguard
      - dogsled
      - dupl
      - errcheck
      - funlen
      - gochecknoglobals
      - gochecknoinits
      - gocognit
      - goconst
      - gocritic
      - gocyclo
      - godox
      - gofmt
      - goimports
      - golint
      - goprintffuncname
      - gosec
      - gosimple
      - govet
      - ineffassign
      - interfacer
      - lll
      - maligned
      - misspell
      - nakedret
      - prealloc
      - rowserrcheck
      - scopelint
      - staticcheck
      - structcheck
      - stylecheck
      - typecheck
      - unconvert
      - unparam
      - unused
      - varcheck
      - whitespace
      - wsl
  
  run:
    timeout: 5m
    skip-dirs:
      - .github
  
  issues:
    max-same-issues: 0
    exclude-use-default: false