name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.15.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x

      - name: Check out code
        uses: actions/checkout@v2

      - name: Check for .golangci.yml file
        id: golangci-check
        uses: andstor/file-existence-action@v1
        with:
          files: .golangci.yaml

      - name: Go Lint
        if: steps.golangci-check.outputs.files_exists == 'true'
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.32