name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.15.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x

      - name: Check out code
        uses: actions/checkout@v2

      - name: Check for .codecov.yaml file
        id: codecov-check
        uses: andstor/file-existence-action@v1
        with:
          files: .codecov.yaml

      - name: Produce Go Coverage
        if: steps.codecov-check.outputs.files_exists == 'true'
        run: echo 'COVER_OPTS=-coverprofile=coverage.txt -covermode=atomic' >> $GITHUB_ENV

      - name: Go Test
        run: go test -race $COVER_OPTS ./...

      - name: Run Codecov
        if: steps.codecov-check.outputs.files_exists == 'true'
        uses: codecov/codecov-action@v1